"""empty message

Revision ID: 31a49886aac9
Revises: cc7888bd99a1
Create Date: 2026-03-23 17:48:17.806886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31a49886aac9'
down_revision: Union[str, Sequence[str], None] = 'cc7888bd99a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activity_type') THEN
                CREATE TYPE "activity_type" AS ENUM ('steps', 'workout_minutes', 'workout_session', 'calories_burned', 'weight', 'custom');
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activity_status') THEN
                CREATE TYPE "activity_status" AS ENUM ('pending', 'in_progress', 'completed', 'overdue');
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'biometric_type') THEN
                CREATE TYPE "biometric_type" AS ENUM ('heart_rate_bpm', 'workout_session', 'weight_kg', 'steps_per_day', 'calories_per_day');
            END IF;
        END $$;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('activity_type', sa.Enum('steps', 'workout_minutes', 'workout_session', 'calories_burned', 'weight', 'custom', name="activity_type"), nullable=False))
    op.add_column('activities', sa.Column('target_value', sa.Integer(), nullable=False))
    op.add_column('activities', sa.Column('progress_value', sa.Integer(), nullable=False))
    op.add_column('activities', sa.Column('unit', sa.String(length=40), nullable=False))
    op.add_column('activities', sa.Column('due_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('activities', sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'overdue', name='activity_status'), nullable=False))
    op.alter_column('refresh_tokens', 'expireTime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'expireTime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('activities', 'status')
    op.drop_column('activities', 'due_at')
    op.drop_column('activities', 'unit')
    op.drop_column('activities', 'progress_value')
    op.drop_column('activities', 'target_value')
    op.drop_column('activities', 'activity_type')
    # ### end Alembic commands ###
