"""biometric + preferences + coach_link

Revision ID: 7753a0be40fc
Revises: ed00e480681d
Create Date: 2026-02-21 23:10:15.301514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision: str = '7753a0be40fc'
down_revision: Union[str, Sequence[str], None] = 'ed00e480681d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_type_enum = postgresql.ENUM('Client', 'Coach', name='usertype')
biometrics_enum = postgresql.ENUM('heart_rate_bpm', 'workout_session', 'weight_kg', 'steps_per_day', 'calories_per_day', name='biometricstype')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('biometrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('biometric_type', biometrics_enum, nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_float', sa.Float(), nullable=True),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometrics_biometric_type'), 'biometrics', ['biometric_type'], unique=False)
    op.create_index(op.f('ix_biometrics_recorded_at'), 'biometrics', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_biometrics_user_id'), 'biometrics', ['user_id'], unique=False)
    op.create_table('coaches',
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coach_id', 'client_id')
    )
    op.create_table('preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preference_info', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )

    #looks for existing types and add if not existant
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'usertype') THEN
                CREATE TYPE "usertype" AS ENUM ('Client', 'Coach');
            END IF;
        END $$;
    """)

    op.execute("""
        ALTER TABLE users 
        ALTER COLUMN "userType" 
        TYPE "usertype" 
        USING "userType"::usertype;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'userType',
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.drop_table('preferences')
    op.drop_table('coaches')
    op.drop_index(op.f('ix_biometrics_user_id'), table_name='biometrics')
    op.drop_index(op.f('ix_biometrics_recorded_at'), table_name='biometrics')
    op.drop_index(op.f('ix_biometrics_biometric_type'), table_name='biometrics')
    op.drop_table('biometrics')
    # ### end Alembic commands ###
