"""added user Auth type

Revision ID: 7f95e7f5cfe2
Revises: 7753a0be40fc
Create Date: 2026-03-01 23:50:26.248778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f95e7f5cfe2'
down_revision: Union[str, Sequence[str], None] = '7753a0be40fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

auth_provider = postgresql.ENUM('Google', 'Local', name='authprovider')

def upgrade() -> None:
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'authprovider') THEN
                CREATE TYPE "authprovider" AS ENUM ('Google', 'Local');
            END IF;
        END $$;
    """)

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authProvider', auth_provider, nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(length=50), nullable=True))
    op.alter_column('users', 'hashedPass',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.execute(
        """
        DO $$
        BEGIN
            UPDATE users
            SET "authProvider" = 'Local'
            WHERE "authProvider" IS NULL;
        END $$; 
    """)
    op.alter_column('users', 'authProvider',
        nullable=False)

    

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashedPass',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'authProvider')
    # ### end Alembic commands ###
