"""changes usertype schema to an "isCoach" boolean flag

Revision ID: a325c04dd62b
Revises: 7f95e7f5cfe2
Create Date: 2026-03-04 19:49:18.860324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a325c04dd62b'
down_revision: Union[str, Sequence[str], None] = '7f95e7f5cfe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_coach', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET is_coach = True WHERE "userType" = \'Coach\'')
    op.execute('UPDATE users SET is_coach = False WHERE "userType" = \'Client\'')
    op.alter_column('users', 'is_coach', nullable=False)

    op.drop_column('users', 'userType')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userType', postgresql.ENUM('Client', 'Coach', name='usertype'), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_coach')
    # ### end Alembic commands ###
