"""empty message

Revision ID: a3aaa1ca6061
Revises: 5da3430e7c1e
Create Date: 2026-03-16 13:50:56.883038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3aaa1ca6061'
down_revision: Union[str, Sequence[str], None] = '5da3430e7c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add as nullable
    op.add_column('activities', sa.Column('assigned_by_id', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('assigned_by_coach', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'activities', 'users', ['assigned_by_id'], ['id'])

    # Step 2: (Optional) Populate for existing rows if needed
    # Example: Set to NULL (or set to a valid user id or boolean if you want)
    # from sqlalchemy.sql import table, column
    # activities = table('activities', column('assigned_by_id', sa.Integer), column('assigned_by_coach', sa.Boolean))
    # op.execute(activities.update().values(assigned_by_id=None, assigned_by_coach=None))

    # Step 3: Alter to NOT NULL
    op.alter_column('activities', 'assigned_by_id', nullable=False)
    op.alter_column('activities', 'assigned_by_coach', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'assigned_by_coach')
    op.drop_column('activities', 'assigned_by_id')
    # ### end Alembic commands ###
