"""initial schema

Revision ID: b2f24f7c50cc
Revises: 
Create Date: 2026-03-24 14:48:02.827946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f24f7c50cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('hashedPass', sa.String(length=255), nullable=True),
    sa.Column('is_coach', sa.Boolean(), nullable=False),
    sa.Column('authProvider', sa.Enum('Local', 'Google', name='authprovider'), nullable=False),
    sa.Column('google_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_coach', sa.Boolean(), nullable=False),
    sa.Column('activity_type', sa.Enum('steps', 'workout_minutes', 'workout_session', 'calories_burned', 'weight', 'custom', name='activitytype'), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('progress_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'overdue', name='activitystatus'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biometrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('biometric_type', sa.Enum('heart_rate_bpm', 'workout_session', 'weight_kg', 'steps_per_day', 'calories_per_day', name='biometrictype'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_float', sa.Float(), nullable=True),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometrics_biometric_type'), 'biometrics', ['biometric_type'], unique=False)
    op.create_index(op.f('ix_biometrics_recorded_at'), 'biometrics', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_biometrics_user_id'), 'biometrics', ['user_id'], unique=False)
    op.create_table('coach_info',
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('focus', sa.String(length=200), nullable=True),
    sa.Column('specialties', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coach_id')
    )
    op.create_table('coach_messages',
    sa.Column('user_1', sa.Integer(), nullable=False),
    sa.Column('user_2', sa.Integer(), nullable=False),
    sa.Column('time_sent', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['user_1'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_2'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_1', 'user_2', 'time_sent')
    )
    op.create_table('coaches',
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coach_id', 'client_id')
    )
    op.create_table('coachinvites',
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coach_id', 'client_id')
    )
    op.create_table('preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preference_info', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expireTime', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_title', sa.String(length=50), nullable=False),
    sa.Column('session_desc', sa.String(length=500), nullable=False),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coach_id', 'client_id', 'date_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('refresh_tokens')
    op.drop_table('preferences')
    op.drop_table('coachinvites')
    op.drop_table('coaches')
    op.drop_table('coach_messages')
    op.drop_table('coach_info')
    op.drop_index(op.f('ix_biometrics_user_id'), table_name='biometrics')
    op.drop_index(op.f('ix_biometrics_recorded_at'), table_name='biometrics')
    op.drop_index(op.f('ix_biometrics_biometric_type'), table_name='biometrics')
    op.drop_table('biometrics')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('items')
    # ### end Alembic commands ###
