"""empty message

Revision ID: cc7888bd99a1
Revises: 43da80a3e585
Create Date: 2026-03-21 23:57:35.708065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc7888bd99a1'
down_revision: Union[str, Sequence[str], None] = '43da80a3e585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_messages',
    sa.Column('user_1', sa.Integer(), nullable=False),
    sa.Column('user_2', sa.Integer(), nullable=False),
    sa.Column('time_sent', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['user_1'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_2'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_1', 'user_2', 'time_sent')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coach_messages')
    # ### end Alembic commands ###
