"""added user type + realtionships

Revision ID: ed00e480681d
Revises: 3bfd41d01365
Create Date: 2026-02-11 22:24:33.976198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed00e480681d'
down_revision: Union[str, Sequence[str], None] = '3bfd41d01365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expireTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### creates userType field ensures a value is included (Default Client)
    op.add_column('users', sa.Column('userType', sa.String(length=15), nullable=True))
    op.execute('UPDATE users SET "userType" = \'Client\'')
    op.alter_column('users', 'userType', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userType')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
